apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-image-leeroy-web
spec:
  type: image
  params:
    - name: url
      value: gcr.io/playground-s-11-f3a1aa18/leeroy-web #configure: replace with where the image should go: perhaps your local registry or Dockerhub with a secret and configured service account